In [38]:
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
import numpy as np
from sklearn.compose import make_column_selector, ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder, PolynomialFeatures, FunctionTransformer
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.model_selection import train_test_split
import warnings
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import accuracy_score, roc_auc_score, classification_report, confusion_matrix, mean_squared_error
from sklearn.model_selection import cross_val_score, GridSearchCV, StratifiedKFold
import matplotlib.pyplot as plt
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.exceptions import FitFailedWarning
from sklearn.svm import SVC
from sklearn.tree import plot_tree
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet 
from sklearn.pipeline import Pipeline, FeatureUnion

In [48]:
train= pd.read_csv("C:/Users/hblin/OneDrive - Cal Poly/GSB 544/Kaggle/gsb-544-fall-2024-political-affiliations/CAH-201803-train.csv")

In [49]:
X = train.drop(["id_num", "political_affiliation"], axis= 1)

y= train["political_affiliation"]

In [50]:
test_data = pd.read_csv("C:/Users/hblin/OneDrive - Cal Poly/GSB 544/Kaggle/gsb-544-fall-2024-political-affiliations/CAH-201803-test.csv")

In [9]:
# Define the preprocessing step
ct = ColumnTransformer(
    [
        ("dummify", 
         OneHotEncoder(sparse_output=False, handle_unknown='ignore'),
         make_column_selector(dtype_include=object)),
        ("standardize", 
         StandardScaler(), 
         make_column_selector(dtype_include=np.number))
    ],
    remainder="passthrough"
).set_output(transform="pandas")

def evaluate_grid_search(grid_search, X, y):
    """
    This function performs grid search, evaluates the best model, and prints the results.

    Parameters:
    - grid_search: The GridSearchCV object that has been set up with the pipeline and parameter grid.
    - X: The feature matrix.
    - y: The target vector.

    Returns:
    - None
    """
    # Suppress warnings only in this block
    with warnings.catch_warnings():
        warnings.simplefilter("ignore", FitFailedWarning)
        grid_search.fit(X, y)  # Perform GridSearchCV without warnings

    # Output the best parameters and ROC-AUC score
    print("Best Parameters:", grid_search.best_params_)
    print(f"Best Cross-validated Metric: {grid_search.best_score_:.4f}")

    # Make predictions with the best estimator
    y_pred = grid_search.best_estimator_.predict(X)

    # Print the classification report and confusion matrix
    print("Classification Report:")
    print(classification_report(y, y_pred))

    print("Confusion Matrix:")
    print(confusion_matrix(y, y_pred))



# Politics

# Logistic

In [117]:
param_grid = {
    "lgr__C": (1,.01,.001),  # Regularization strength (covers a wider range)
    "lgr__penalty": ["l1","none"],  # Adding "none" to include no regularization
    "lgr__solver": ["lbfgs", "liblinear"],  # Adding all solvers supported
    "lgr__class_weight": [None, "balanced"],  # Adjust weights for imbalanced data
    "lgr__l1_ratio": (.1, 0.001, 1),  # ElasticNet mix ratio (used with solver="saga")
}

lgr_pipeline = Pipeline(
    [("preprocessing", ct),
     ("lgr", LogisticRegression())]  # Default classifier
)

grid_search = GridSearchCV(
    lgr_pipeline,
    param_grid,
    cv=5,  # Ensures proper class distribution
    scoring="accuracy",
    n_jobs=-1
)
evaluate_grid_search(grid_search, X, y)

Best Parameters: {'lgr__C': 1, 'lgr__class_weight': 'balanced', 'lgr__l1_ratio': 0.1, 'lgr__penalty': 'l1', 'lgr__solver': 'liblinear'}
Best Cross-validated Metric: 0.6275
Classification Report:
              precision    recall  f1-score   support

    Democrat       0.68      0.75      0.71        59
 Independent       0.65      0.59      0.62        56
  Republican       0.79      0.78      0.79        54

    accuracy                           0.70       169
   macro avg       0.71      0.70      0.70       169
weighted avg       0.70      0.70      0.70       169

Confusion Matrix:
[[44 12  3]
 [15 33  8]
 [ 6  6 42]]


c:\Users\hblin\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\model_selection\_search.py:1103: UserWarning: One or more of the test scores are non-finite: [       nan 0.62156863        nan        nan        nan 0.62156863
        nan        nan        nan 0.62156863        nan        nan
        nan 0.62745098        nan        nan        nan 0.62745098
        nan        nan        nan 0.62745098        nan        nan
        nan 0.34919786        nan        nan        nan 0.34919786
        nan        nan        nan 0.34919786        nan        nan
        nan 0.34919786        nan        nan        nan 0.34919786
        nan        nan        nan 0.34919786        nan        nan
        nan 0.34919786        nan        nan        nan 0.34919786
        nan        nan        nan 0.34919786        nan        nan
        nan 0.34919786        nan        nan        nan 0.34919786
        nan        nan        nan 0.34919786        nan        nan]
  warnings.warn(
c:\U

In [ ]:
fin_param_grid = {
    "lgr__C": [1],  # Regularization strength
    "lgr__class_weight": ["balanced"],  # Adjust weights based on class frequencies
    "lgr__l1_ratio": [0.1],  # ElasticNet mixing parameter (only relevant if 'elasticnet' is used)
    "lgr__penalty": ["l2"],
    "lgr__solver": ["liblinear"]  # Solver
}

lgr_pipeline = Pipeline(
    [("preprocessing", ct),
     ("lgr", LogisticRegression())]  # Default classifier
)

final_model_fit = GridSearchCV(
    lgr_pipeline,
    fin_param_grid,
    cv=5,
    scoring="accuracy",
    n_jobs=-1
)
evaluate_grid_search(final_model_fit, X, y)

Best Parameters: {'lgr__C': 1, 'lgr__class_weight': 'balanced', 'lgr__l1_ratio': 0.1, 'lgr__penalty': 'l2', 'lgr__solver': 'liblinear'}
Best Cross-validated Metric: 0.6332
Classification Report:
              precision    recall  f1-score   support

    Democrat       0.68      0.73      0.70        59
 Independent       0.67      0.64      0.65        56
  Republican       0.81      0.78      0.79        54

    accuracy                           0.72       169
   macro avg       0.72      0.72      0.72       169
weighted avg       0.72      0.72      0.72       169

Confusion Matrix:
[[43 13  3]
 [13 36  7]
 [ 7  5 42]]


c:\Users\hblin\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(


# Decision Tree

In [27]:
param_grid = {
    "dt__max_depth": list(range(3, 11)) + [None],  # Integer range from 3 to 10, plus None for no limit
    "dt__min_samples_split": list(range(2, 21)),  # Integer range from 2 to 20
    "dt__min_samples_leaf": list(range(1, 11)),   # Integer range from 1 to 10
    "dt__criterion": ["gini", "entropy"]          # Keep these as discrete choices
}

# Define the pipeline with DecisionTreeClassifier
dt_pipeline = Pipeline(
    [("preprocessing", ct),
     ("dt", DecisionTreeClassifier())]
)

# Set up GridSearchCV for cross-validation and hyperparameter search
grid_search = GridSearchCV(dt_pipeline, param_grid, cv=StratifiedKFold(n_splits=5), scoring='accuracy', n_jobs=-1)

# Fit the GridSearchCV with your data
grid_search.fit(X, y)
evaluate_grid_search(grid_search, X, y)

Best Parameters: {'dt__criterion': 'entropy', 'dt__max_depth': 5, 'dt__min_samples_leaf': 2, 'dt__min_samples_split': 4}
Best Cross-validated Metric: 0.6157
Classification Report:
              precision    recall  f1-score   support

    Democrat       0.72      0.83      0.77        59
 Independent       0.73      0.68      0.70        56
  Republican       0.94      0.85      0.89        54

    accuracy                           0.79       169
   macro avg       0.80      0.79      0.79       169
weighted avg       0.79      0.79      0.79       169

Confusion Matrix:
[[49  8  2]
 [17 38  1]
 [ 2  6 46]]


In [121]:
final_predictions = pd.DataFrame(
    {"id_num": test_data['id_num'],
    "political_affiliation_predicted": final_model_fit.predict(test_data)}
)


# Houses

In [ ]:
train = pd.read_csv("C:/Users/hblin/OneDrive - Cal Poly/GSB 544/Kaggle/gsb-544-fall-2024-house-prices/train_new.csv")

test = pd.read_csv("C:/Users/hblin/OneDrive - Cal Poly/GSB 544/Kaggle/gsb-544-fall-2024-house-prices/test_new.csv")

train_clean = train.dropna()

train_clean['logSalePrice'] = np.log(train_clean['SalePrice'])

C:\Users\hblin\AppData\Local\Temp\ipykernel_32352\1427950668.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_clean['logSalePrice'] = np.log(train_clean['SalePrice'])


In [72]:
X = train_clean.drop(["SalePrice",'logSalePrice',"PID"], axis= 1)

y = train_clean["logSalePrice"]


In [13]:
# Define the preprocessing step
ct = ColumnTransformer(
    [
        ("dummify", 
         OneHotEncoder(sparse_output=False, handle_unknown='ignore'),
         make_column_selector(dtype_include=object)),
        ("standardize", 
         StandardScaler(), 
         make_column_selector(dtype_include=np.number))
    ],
    remainder="passthrough"
).set_output(transform="pandas")

## Linear Regression

In [34]:

lr_pipeline = Pipeline(
  [("preprocessing", ct), # Polynomial features before linear regression
   ("lr", LinearRegression())]  # Linear regression after polynomial features
)

# Fit the model on the full dataset
lr_pipeline_fit = lr_pipeline.fit(X, y)

# Predict on the same data
y_pred = lr_pipeline.predict(X)

# Calculate RMSE (Root Mean Squared Error)
mse = mean_squared_error(y, y_pred)
rmse = np.sqrt(mse)
print("Linear Regression RMSE:", rmse)

# Perform cross-validation with negative RMSE scoring
cross_val_rmse_neg = cross_val_score(lr_pipeline, X, y, cv=5, scoring='neg_root_mean_squared_error').mean()

# Convert negative RMSE to positive RMSE
cross_val_rmse = -cross_val_rmse_neg  # Make the RMSE positive
print(f"Cross-validated RMSE: {cross_val_rmse}")


Linear Regression RMSE: 0.1386362024849966
Cross-validated RMSE: 14518516687.974293


In [36]:
# Adjust the pipeline and fit the model
lr_pipeline = Pipeline(
    [("preprocessing", ct),  # Preprocessing step
     ("lr", Ridge(alpha=1))]  # Use Ridge regression to apply regularization
)

# Fit the model on the full dataset
lr_pipeline_fit = lr_pipeline.fit(X, y)

# Predict on the same data
y_pred = lr_pipeline.predict(X)

# Calculate RMSE (Root Mean Squared Error)
mse = mean_squared_error(y, y_pred)
rmse = np.sqrt(mse)
print("Linear Regression RMSE:", rmse)

# Perform cross-validation with negative RMSE scoring
cross_val_rmse_neg = cross_val_score(lr_pipeline, X, y, cv=5, scoring='neg_root_mean_squared_error').mean()

# Convert negative RMSE to positive RMSE
cross_val_rmse = -cross_val_rmse_neg  # Make the RMSE positive
print(f"Cross-validated RMSE: {cross_val_rmse}")


Linear Regression RMSE: 0.13972939605407306
Cross-validated RMSE: 0.15312559584145574


In [59]:

def add_squared_feature(X):
    X = X.copy()
    X['gr_liv_area_squared'] = X['Gr Liv Area'] ** 2
    X['TotRms_AbvGrd_squared'] = X['TotRms AbvGrd'] ** 2
    return X

# Define the transformation for the new squared feature
square_transformer = FunctionTransformer(add_squared_feature)

# Create a preprocessing pipeline
ct = ColumnTransformer([
    ("dummify", OneHotEncoder(sparse_output=False, handle_unknown='ignore'), make_column_selector(dtype_include=object)),
    ("standardize", StandardScaler(), make_column_selector(dtype_include=np.number))
], remainder="passthrough").set_output(transform="pandas")

# Define the pipeline with the custom transformer and Ridge regression
lr_pipeline = Pipeline([
    ("add_squared_feature", square_transformer),  # Add squared feature step
    ("preprocessing", ct),  # Preprocessing step
    ("lr", Ridge())  # Use Ridge regression to apply regularization
])

# Fit the model on the full dataset
lr_pipeline.fit(X, y)

# Predict on the same data
y_pred = lr_pipeline.predict(X)

# Calculate RMSE (Root Mean Squared Error)
mse = mean_squared_error(y, y_pred)
rmse = np.sqrt(mse)
print("Ridge Regression RMSE:", rmse)

# Perform cross-validation with negative RMSE scoring
cross_val_rmse_neg = cross_val_score(lr_pipeline, X, y, cv=5, scoring='neg_root_mean_squared_error').mean()

# Convert negative RMSE to positive RMSE
cross_val_rmse = -cross_val_rmse_neg  # Make the RMSE positive
print(f"Cross-validated RMSE: {cross_val_rmse}")


Ridge Regression RMSE: 0.12585915832380812
Cross-validated RMSE: 0.14149225057728243


In [76]:

def add_squared_feature(X):
    X = X.copy()
    X['gr_liv_area_squared'] = X['Gr Liv Area'] ** 2
    X['TotRms_AbvGrd_squared'] = X['TotRms AbvGrd'] ** 2
    X['Yr Sold'] = X['Yr Sold'] ** 2
    return X

# Define the transformation for the new squared feature
square_transformer = FunctionTransformer(add_squared_feature)

# Create a preprocessing pipeline
ct = ColumnTransformer([
    ("dummify", OneHotEncoder(sparse_output=False, handle_unknown='ignore'), make_column_selector(dtype_include=object)),
    ("standardize", StandardScaler(), make_column_selector(dtype_include=np.number))
], remainder="passthrough").set_output(transform="pandas")

# Define the pipeline with the custom transformer and Ridge regression
lr_pipeline = Pipeline([
    ("add_squared_feature", square_transformer),  # Add squared feature step
    ("preprocessing", ct),  # Preprocessing step
    ("lr", Ridge())  # Use Ridge regression to apply regularization
])

# Fit the model on the full dataset
lr_pipeline.fit(X, y)

# Predict on the same data
y_pred = lr_pipeline.predict(X)

# Calculate RMSE (Root Mean Squared Error)
mse = mean_squared_error(y, y_pred)
rmse = np.sqrt(mse)
print("Ridge Regression RMSE:", rmse)

# Perform cross-validation with negative RMSE scoring
cross_val_rmse_neg = cross_val_score(lr_pipeline, X, y, cv=5, scoring='neg_root_mean_squared_error').mean()

# Convert negative RMSE to positive RMSE
cross_val_rmse = -cross_val_rmse_neg  # Make the RMSE positive
print(f"Cross-validated RMSE: {cross_val_rmse}")


Ridge Regression RMSE: 0.1258591671401557
Cross-validated RMSE: 0.14149226662084133


In [85]:
test_predictions = grid_search.predict(test)

# Create a DataFrame for the predictions
predictions_df_2 = pd.DataFrame(test_predictions, columns=['SalePrice'])

# Add the 'PID' variable from the test DataFrame
predictions_df_2['PID'] = test['PID']

# Exponentiate the Predicted_SalePrice
predictions_df_2['SalePrice'] = np.exp(predictions_df_2['SalePrice'])

# Reorder the columns so PID is first (optional)
predictions_df_2 = predictions_df_2[['PID', 'SalePrice']]

# Display the resulting DataFrame
print(predictions_df_2)


           PID      SalePrice
0    907135180  129121.422430
1    528181040  198669.734524
2    528175010  202149.761402
3    531379030  189110.857786
4    923275090  134914.334307
..         ...            ...
600  528174060  185396.629606
601  903400180  166333.109367
602  903227150  142451.111832
603  909250070  131226.847637
604  909425180  212030.918876

[605 rows x 2 columns]


In [84]:
knn_pipeline = Pipeline(
  [("add_squared_feature", square_transformer),
    ("preprocessing", ct),
    ("knn", KNeighborsRegressor(n_neighbors=5))]
)

knn_pipeline.fit(X,y)

y_pred = knn_pipeline.predict(X)

# Calculate RMSE (Root Mean Squared Error)
mse = mean_squared_error(y, y_pred)
rmse = np.sqrt(mse)
print("Ridge Regression RMSE:", rmse)

# Perform cross-validation with negative RMSE scoring
cross_val_rmse_neg = cross_val_score(knn_pipeline, X, y, cv=5, scoring='neg_root_mean_squared_error').mean()

# Convert negative RMSE to positive RMSE
cross_val_rmse = -cross_val_rmse_neg  # Make the RMSE positive
print(f"Cross-validated RMSE: {cross_val_rmse}")

from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsRegressor

# Define the hyperparameter grid
param_grid = {
    'knn__n_neighbors': [5],
    'knn__weights': ['distance'],
    'knn__metric': ['manhattan']
}

# Perform GridSearchCV
grid_search = GridSearchCV(knn_pipeline, param_grid, cv=5, scoring='neg_root_mean_squared_error', n_jobs=-1)
grid_search.fit(X, y)

# Get the best parameters and RMSE
best_params = grid_search.best_params_
best_rmse = -grid_search.best_score_

print("Best Parameters:", best_params)
print(f"Best Cross-validated RMSE: {best_rmse}")


Ridge Regression RMSE: 0.13817894042490236
Cross-validated RMSE: 0.17555797075710075
Best Parameters: {'knn__metric': 'manhattan', 'knn__n_neighbors': 5, 'knn__weights': 'distance'}
Best Cross-validated RMSE: 0.1654955247080679
